### ISSUE TITLE
Only specifying totally overlapped set elements in the overlap causes a TypeError

### ISSUE THREAD

**Issue by jimjam-slam** [upsetjs/venn.js#39]
When I try to build a Venn diagram using elements that only appear in intersections (ie. it is totally overlapped by another element), I get an error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'size')
    at greedyLayout (venn.js:1140:58)
    at bestInitialLayout (venn.js:1019:19)
    at venn (venn.js:792:21)
    at chart (venn.js:1745:24)
    at Selection$1.selection_call [as call] (d3.v6.js:1747:12)
    at test.html:20:42
```

Adding the overlapped elements on their own fixes the problem, but it does mean I end up with duplicate labels that I would rather avoid if possible (although I suppose I can omit them by changing the label to a space if I manually identify the culprits).

**To Reproduce**

```html
<html>
  <head>
  </head>
  <body>
    <script src="https://d3js.org/d3.v6.js"></script>
    <script src="node_modules/@upsetjs/venn.js/build/venn.js"></script>

    <div id="venn"></div>
    <script>

      var setsTest = [
        { sets: ["Apple", "Banana"], label: "Apple and Banana: 1", size: 1 },
        { sets: ["Orange"], label: "Orange: 8", size: 8 },
        { sets: ["Orange", "Kiwi"], label: "Orange and Kiwi: 1", size: 1 },
        { sets: ["Banana"], label: "Banana: 3", size: 3 },
        // { sets: ["Apple"], label: "Apple: 1", size: 1 },
        // { sets: ["Kiwi"], label: "Kiwi: 1", "size": 1 },
      ];
      var chart = venn.VennDiagram();
      d3.select('#venn').datum(setsTest).call(chart);

    </script>
  </body>
```

With the commented lines above uncommented:

![image](https://user-images.githubusercontent.com/6520659/163306168-f8ccb584-e439-4cdf-876b-9e4367cfe101.png)

**Context**

- Version: 1.4.2
- Browser: Microsoft Edge 97.0.1072.76 (arm64)

**Comment by jimjam-slam** [comment]
Sorry, I just realised that this workaround is actually incorrect. I think I've misunderstood how the data should be input - it seems that element sizes should be specified _inclusive_ of overlaps, not _exclusive_. Which explains my problem - I had my data specifying the sizes exclusive of overlaps, and where there was only overlap it was just implicitly missing!
